### ISSUE TITLE
On Debian wheezy it raises SSL errors

### ISSUE THREAD

**Issue by tommics** [zachwill/dom#19]
```
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/usr/local/bin/dom", line 5, in <module>
    pkg_resources.run_script('dom==0.7', 'dom')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/dom-0.7-py2.7.egg/EGG-INFO/scripts/dom", line 7, in <module>
    Domain().main()
  File "/usr/local/lib/python2.7/dist-packages/dom-0.7-py2.7.egg/domainr/core.py", line 83, in main
    print self.search(args)
  File "/usr/local/lib/python2.7/dist-packages/dom-0.7-py2.7.egg/domainr/core.py", line 39, in search
    data = self.parse(json_data.content, env)
  File "/usr/local/lib/python2.7/dist-packages/dom-0.7-py2.7.egg/domainr/core.py", line 48, in parse
    results = data['results']
KeyError: 'results'

```

**Comment by seanlane** [comment]
Looks to be related to the API key errors previously reported. Fixed with PR's #18, #21, and #22; closing.
