### ISSUE TITLE
KeyError: 'results'

### ISSUE THREAD

**Issue by iGaskin** [zachwill/dom#20]
When using the dom tool, I receive a key-error message.

`C02Q21D2FVH9:AWS isaac.gaskin$ dom lol
Traceback (most recent call last):
  File "/usr/local/bin/dom", line 7, in <module>
    Domain().main()
  File "/Library/Python/2.7/site-packages/domainr/core.py", line 83, in main
    print self.search(args)
  File "/Library/Python/2.7/site-packages/domainr/core.py", line 39, in search
    data = self.parse(json_data.content, env)
  File "/Library/Python/2.7/site-packages/domainr/core.py", line 48, in parse
    results = data['results']
KeyError: 'results'
C02Q21D2FVH9:AWS isaac.gaskin$ dom google
Traceback (most recent call last):
  File "/usr/local/bin/dom", line 7, in <module>
    Domain().main()
  File "/Library/Python/2.7/site-packages/domainr/core.py", line 83, in main
    print self.search(args)
  File "/Library/Python/2.7/site-packages/domainr/core.py", line 39, in search
    data = self.parse(json_data.content, env)
  File "/Library/Python/2.7/site-packages/domainr/core.py", line 48, in parse
    results = data['results']
KeyError: 'results'`

**Comment by navisidhu** [comment]
The underlying issue is receiving
`{'message': 'unauthorized: disabled client ID'}`
when authorizing against Domainr API.

**Comment by oliverbenns** [comment]
+1

**Comment by kevinelliott** [comment]
I have this problem as well.

**Comment by rjantos** [comment]
same here. identical error message using python 2.7

**Comment by seanlane** [comment]
Fixed with PR's #18, #21, and #22; closing.
